modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
    modId="thecomfortzone"
    version="${file.jarVersion}"
    displayName="The Comfort Zone"
    logoFile="ur_mom.png"
    credits="Sarinsa (Coding), Frenderman (Art and concepts)"
    authors="Frenderman"
    description="We have pillows"

[[dependencies.thecomfortzone]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thecomfortzone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
